<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260710175523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add friendship, disc_invitation and notification tables.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE disc_invitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disc_id VARCHAR(36) NOT NULL, from_user_id INT NOT NULL, to_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C39DD8AC38F37CA ON disc_invitation (disc_id)');
        $this->addSql('CREATE INDEX IDX_9C39DD8A2130303A ON disc_invitation (from_user_id)');
        $this->addSql('CREATE INDEX IDX_9C39DD8A29F6EE60 ON disc_invitation (to_user_id)');
        $this->addSql('CREATE TABLE friendship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, requester_id INT NOT NULL, addressee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7234A45FED442CF4 ON friendship (requester_id)');
        $this->addSql('CREATE INDEX IDX_7234A45F2261B4C3 ON friendship (addressee_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(40) NOT NULL, data JSON NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id)');
        $this->addSql('ALTER TABLE disc_invitation ADD CONSTRAINT FK_9C39DD8AC38F37CA FOREIGN KEY (disc_id) REFERENCES disc (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disc_invitation ADD CONSTRAINT FK_9C39DD8A2130303A FOREIGN KEY (from_user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disc_invitation ADD CONSTRAINT FK_9C39DD8A29F6EE60 FOREIGN KEY (to_user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45FED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F2261B4C3 FOREIGN KEY (addressee_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE disc_invitation DROP CONSTRAINT FK_9C39DD8AC38F37CA');
        $this->addSql('ALTER TABLE disc_invitation DROP CONSTRAINT FK_9C39DD8A2130303A');
        $this->addSql('ALTER TABLE disc_invitation DROP CONSTRAINT FK_9C39DD8A29F6EE60');
        $this->addSql('ALTER TABLE friendship DROP CONSTRAINT FK_7234A45FED442CF4');
        $this->addSql('ALTER TABLE friendship DROP CONSTRAINT FK_7234A45F2261B4C3');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('DROP TABLE disc_invitation');
        $this->addSql('DROP TABLE friendship');
        $this->addSql('DROP TABLE notification');
    }
}
